begin;

insert into public.app_settings (
  key,
  group_key,
  label,
  help_text,
  rationale,
  source_note,
  value_type,
  text_value,
  numeric_value,
  unit,
  decimals,
  sort_order,
  is_public,
  editable_by_admin
)
values
  (
    'eyebrow',
    'hero',
    'Hero eyebrow',
    'Small uppercase line shown above the car title in the hero.',
    'Keeps the landing section framed as a trip cost tool before the main car title.',
    'Current hero copy.',
    'text',
    'Trip Cost Splitter',
    null,
    '',
    0,
    5,
    true,
    true
  ),
  (
    'description',
    'hero',
    'Hero description',
    'Main supporting paragraph under the car title.',
    'Explains what the calculator does without forcing the user into the constants section.',
    'Current hero copy.',
    'text',
    'A clean way to calculate who owes what for a trip.',
    null,
    '',
    0,
    15,
    true,
    true
  ),
  (
    'badgePrimary',
    'hero',
    'Hero badge 1',
    'First badge shown under the hero description.',
    'Highlights the primary bundled cost components at a glance.',
    'Current hero copy.',
    'text',
    'Fuel + insurance + maintenance',
    null,
    '',
    0,
    85,
    true,
    true
  ),
  (
    'badgeSecondary',
    'hero',
    'Hero badge 2',
    'Second badge shown under the hero description.',
    'Calls out that trip risk is already included in the model.',
    'Current hero copy.',
    'text',
    'Risks included',
    null,
    '',
    0,
    86,
    true,
    true
  ),
  (
    'badgeTertiary',
    'hero',
    'Hero badge 3',
    'Third badge shown under the hero description.',
    'Clarifies the rounding rule before the user calculates a trip.',
    'Current hero copy.',
    'text',
    'Rounded up to the nearest dollar',
    null,
    '',
    0,
    87,
    true,
    true
  ),
  (
    'riskTitle',
    'hero',
    'Risk card title',
    'Headline shown in the yellow risk note card.',
    'Keeps the risk add-on explicit instead of burying it inside the formula.',
    'Current hero copy.',
    'text',
    'Risk coverage matters',
    null,
    '',
    0,
    88,
    true,
    true
  ),
  (
    'riskBody',
    'hero',
    'Risk card body',
    'Supporting text shown in the yellow risk note card.',
    'Explains what the risk charge is intended to cover in plain language.',
    'Current hero copy.',
    'text',
    'Small damage, towing, and cleanup are already built into the cost per km.',
    null,
    '',
    0,
    89,
    true,
    true
  )
on conflict (key) do update
set group_key = excluded.group_key,
    label = excluded.label,
    help_text = excluded.help_text,
    rationale = excluded.rationale,
    source_note = excluded.source_note,
    value_type = excluded.value_type,
    text_value = excluded.text_value,
    numeric_value = excluded.numeric_value,
    unit = excluded.unit,
    decimals = excluded.decimals,
    sort_order = excluded.sort_order,
    is_public = excluded.is_public,
    editable_by_admin = excluded.editable_by_admin;

commit;
